### ISSUE TITLE
[MUST] Show versioned documentation 

### ISSUE THREAD

**Issue by jason-fox** [conwetlab/FIWARE-CKAN-Extensions#14]
On CKAN Extensions ReadtheDocs project, version 7.4.0 is not displayed

* Goto https://readthedocs.org/projects/fiware-ckan-extensions//versions/
* Ensure that active checkmark is ticked against relevant release tags

**Comment by fdelavega** [comment]
It was missing the compilation...

Now it is available:
https://fiware-ckan-extensions.readthedocs.io/en/v7.4.0/

**Comment by jason-fox** [comment]
:+1:
